# Generated by Django 6.1 on 2026-08-17 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=150)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_building', 'Muscle Building'), ('maintenance', 'Maintenance'), ('general_fitness', 'General Fitness')], max_length=30)),
                ('daily_calories', models.FloatField()),
                ('protein_grams', models.FloatField()),
                ('carbohydrate_grams', models.FloatField()),
                ('fat_grams', models.FloatField()),
                ('water_liters', models.FloatField(default=2.0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], max_length=20)),
                ('meal_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('fat', models.FloatField()),
                ('serving_size', models.CharField(blank=True, max_length=100)),
                ('meal_time', models.TimeField(blank=True, null=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.dietplan')),
            ],
        ),
    ]
