# Generated by Django 6.1 on 2026-08-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_muscle', models.CharField(max_length=100)),
                ('equipment', models.CharField(default='None', max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('instructions', models.TextField()),
                ('common_mistakes', models.TextField(blank=True)),
                ('safety_tips', models.TextField(blank=True)),
                ('demonstration', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
