# Generated by Django 6.1 on 2026-08-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='demonstration',
            new_name='demonstration_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='ai_exercise_code',
            field=models.CharField(blank=True, help_text='Example: squat, pushup, lunge', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='demonstration_animation',
            field=models.FileField(blank=True, null=True, upload_to='exercise_animations/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='demonstration_image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_images/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('mobility', 'Mobility'), ('balance', 'Balance'), ('core', 'Core')], default='strength', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_joints',
            field=models.CharField(blank=True, help_text='Example: knee, hip, ankle', max_length=200),
        ),
        migrations.AddField(
            model_name='exercise',
            name='recommended_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='recommended_repetitions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='recommended_sets',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='target_muscle',
            field=models.CharField(max_length=200),
        ),
    ]
